name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/FormGenerator

            git pull origin main

            docker stop form-generator || true
            docker rm form-generator || true

            docker build -t form-generator .

            docker run -d \
              --name form-generator \
              --restart unless-stopped \
              -p 3000:3000 \
              --env-file .env \
              form-generator